services:
  # 1. Base de datos vectorial Chroma
  chroma:
    image: chromadb/chroma:0.6.3          # imagen oficial estable 🗄️
    container_name: chroma
    ports:
      - "8000:8000"                       # API REST de Chroma
    volumes:
      - ./chroma_data:/chroma/chroma      # persistencia local
    environment:
      - IS_PERSISTENT=TRUE                # activa modo disco
      - PERSIST_DIRECTORY=/chroma/chroma  # dónde guardar los vectores
    restart: unless-stopped               # arranca tras un reboot
    healthcheck:                          # <-  ping al endpoint de latido
      test: ["CMD", "curl", "-fs", "http://localhost:8000/api/v1/heartbeat"]
      interval: 5s
      timeout: 3s
      retries: 5
  # 2. Tu aplicación FastAPI
  app:
    build: ./backend                      # usa el Dockerfile que sigue
    container_name: backend
    ports:
      - "8001:8001"                       # expone la API de tu servicio
    environment:
      - CHROMA_HOST=chroma
      - CHROMA_PORT=8000
    depends_on:
      chroma:
        condition: service_healthy        # <- espera a que esté listo
    restart: unless-stopped